### PR TITLE
Remove automatically closing stale issues

### PR DESCRIPTION
**Pull request by ngeiswei**
The day the bot can take over the project then it'll have its say...

...but that day is not today.

### CODE REVIEW

**Comment by ngeiswei** [comment]
@ntoxeg, the idea is cool in principle but I find that it's more cumbersome than useful, so I suggest to remove it.

If you disagree and think it still has a place, maybe better parameterized or such, of course let me know.

**Comment by ngeiswei** [comment]
Maybe we can re-enable it one day when ROCCA is sufficiently advanced, ROCCA-action. ;-)

**Comment by ntoxeg** [comment]
@ngeiswei I know, I’ve noticed that myself — it is certainly better suited to bug reports than “organisational” issues. That said, I can simply reconfigure it to something like “only process Issues that are tagged as ‘bug’” or something.

Also, stale detection for Pull Requests is still nice in case someone just opens a PR and then just leaves it there. In that case you simply don’t have to think about it — if an “outside” PR is not in acceptable shape you can forget about it, because the burden of polishing it is on the poster anyway. It’s certainly overkill for ROCCA now as we don’t have random contributors really. But it doesn’t hurt (I don’t remember anyone, besides me, leaving a PR hanging open for a very  long time).

Anyway, you can delete it, if you want. We can go back to this in the future, when it becomes more relevant.

**Comment by ngeiswei** [comment]
I'm gonna delete it for now, till a smarter version sees the day.

**Comment by ngeiswei** [comment]
@ntoxeg, I think what bothers me the most about this action is the automatic closing after a week, it's either too short or shouldn't be there at all.

**Pull request merged**
