### PR TITLE
Fix the order of variables

### PR DESCRIPTION
**Pull request by tanksha**
The reward and observation variables were reversed.

### CODE REVIEW

**Review by ntoxeg — CHANGES_REQUESTED** [review]
This is wrong, `parse_world_state` from `GymWrapper` now returns (_observation, reward, done_), not (_reward, observation, done_). I changed this a while back to make everything consistent with the Gym ordering — that fact is now propagated all the way back to the base `Wrapper` class.

Unless there is a strong reason to bring this back to the old way I would suggest not reversing these again.

**Comment by ntoxeg** [comment]
Ah, I see, the `MalmoWrapper` is not adjusted, I didn’t take that into account, sorry. I will send a patch for that.

**Comment by tanksha** [comment]
The MalmoWrapper `parse_world_state` returns [reward, observation, done] but I saw #37 fixes it. Closing this PR.

**Comment by ngeiswei** [comment]
@ntoxeg, the error
```
Torch not found, torch truth value will not be available
```
Indicates that your image is using the singnet fork of atomspace.  Since that PR is for opencog/rocca, I assume it is better to use opencog/atomspace as well.  Likewise, perhaps ideally we'd want to have singnet/rocca integration test to use an image with singnet/atomspace, even though given that singnet/atomspace offers nothing that rocca uses at that point, it doesn't really matter (I'm frequently merge opencog/atomspace into singnet/atomspace anyway).

**Comment by ntoxeg** [comment]
@ngeiswei yes, it would make sense but I need to figure out how to setup a workflow that handles this logic, as I can’t make a different workflow in a fork, maybe it’s possible to have two workflow files and use repository settings to manually choose one or the other, I don’t know yet.

**Comment by ngeiswei** [comment]
@ntoxeg, for atomspace and such we addressed that by using circleci variables in the config file.  See for instance https://github.com/opencog/atomspace/blob/b5b31542217ae9d44eeee29c475646b5726e60b0/.circleci/config.yml#L6.  But as I said, since opencog/rocca and singnet/rocca usually mirror each other (and if not, it is short lived), I think it's acceptable if you use one image for both, preferably opencog's since singnet tends to be lagging a bit behind.

**Comment by ntoxeg** [comment]
@ngeiswei I can’t use the fix you posted because I’m a single user on DockerHub — that solution relies on the fact that you have `opencog` and `singnet` organisations existing there. I’ll just change to use `opencog` repositories since you’ve said it lags behind a bit. I might figure something out later but it also means I have to produce more images.

**Pull request closed without merging**
