### PR TITLE
Fix MalmoWrapper observation / reward order

### PR DESCRIPTION
**Pull request by ntoxeg**
+ regenerate library from notebooks
+ reformat code

This properly fixes #36.

### CODE REVIEW

**Comment by ntoxeg** [comment]
Bad news: because of the new type annotations I have to upgrade Python in the docker image (not trivial). Until that is done all test will be failing.

**Comment by ntoxeg** [comment]
I have a solution to build against Python 3.10 in my images in the works, hopefully tests will be working soon.

**Comment by ntoxeg** [comment]
I have absolutely no idea why pip still fails in the workflow, this is exactly the problem I have fixed in the image now.

**Comment by ntoxeg** [comment]
I’m done for today but I’ve figured out what’s wrong — there are quite a few problems with GitHub Actions idiosyncrasies, I’ll slowly deal with those.

**Comment by ntoxeg** [comment]
@ngeiswei oof, `pip` finally works in Github Actions. At this point you can just merge this PR as I went out of scope already.

There are more issues to fix but they are less confusing — like some packages not installing because they build from source (for some reason) and missing development packages. There is also the fact that `FindCython` brakes in AtomSpace, so the whole thing is not buildable currently. That will take more work but this Actions workflow is now correct — the rest of fixing will be on my Docker image-side, so there is nothing more to do here.

**Comment by ngeiswei** [comment]
Thanks @ntoxeg !

**Pull request merged**
