### PR TITLE
Fix total count and more

### PR DESCRIPTION
**Pull request by ngeiswei**

### CODE REVIEW

**Comment by ngeiswei** [comment]
@ntoxeg, I'm getting the following CI error 

https://github.com/opencog/rocca/runs/5021235932?check_suite_focus=true#step:6:254

any idea?

**Comment by ngeiswei** [comment]
The problem does not seem to be related to rocca itself, so I'm merging.

**Comment by ntoxeg** [comment]
@ngeiswei beats me, I’ll have to investigate.

**Comment by ngeiswei** [comment]
Not sure it has anything to do with this, but I've recently moved the min version of Python to 3.10.

**Comment by ntoxeg** [comment]
@ngeiswei it seems there are some changes to how `setuptools` works, I’m testing a workaround now (it seems they broke something for now).

**Pull request merged**
